### ISSUE TITLE
reverse proxy - Traefik

### ISSUE THREAD

**Issue by ilsaul** [hakwerk/labca#136]
Hi,
I use a reverse proxy to setup any container and I have to do it with labca.
I use Traefik and for this I need to insert some labels in the container script.
Exist this system too: https://docs.docker.com/compose/multiple-compose-files/merge/ with compose.override.yml
How can I use it with your system? I used the command 'curl -sSL https://raw.githubusercontent.com/hakwerk/labca/master/install | bash'

thank you

**Comment by ilsaul** [comment]
I add my docker-compose.override.yml
services:
  nginx:
    networks:
      - rproxy
    labels:
      traefik.enable: true
      traefik.http.routers.labca.rule: Host(`labca.mydomain.com`)
      traefik.http.routers.labca.entryPoints: websecure
      traefik.http.routers.labca.service: labca
      traefik.http.routers.labca.tls: true
      traefik.http.services.labca.loadbalancer.server.port: 80

networks:
  rproxy:
    name: traefik
    external: true

but not working.

**Comment by hakwerk** [comment]
I have no experience with override files. Perhaps the `networks:` field of the nginx service in the override file is **replacing** the networks instead of **appending**?
You could try putting this in your `compose.override.yml`:
```
    networks:
      - bouldernet
      - rproxy
```

---

> but not working.

Normally the error message should give you some clue what is wrong...
