### ISSUE TITLE
Audit Errors even though the LabCA machine certificate generated properly

### ISSUE THREAD

**Issue by patanne** [hakwerk/labca#26]
I have a problem, it seems, and am beginning here, without uploading an endless supply of logs. I am happy to provide what is needed but don't want to bury people with the superfluous.

I am getting many errors of the following: 

`[AUDIT] [core]grpc: addrConn.createTransport failed to connect to  {10.88.88.88:9093 ca.boulder:9093 <nil> 0 <nil>}.`

`[AUDIT] [core]grpc: addrConn.createTransport failed to connect to {10.77.77.77:9093 ca.boulder:9093 <nil> 0 <nil>}.`

`[AUDIT] [core]grpc: addrConn.createTransport failed to connect to {10.77.77.77:9096 ca.boulder:9096 <nil> 0 <nil>}.`

Each of these errors has an accompanying error that begins with...

`[AUDIT] [core]grpc: Server.Serve failed to complete security handshake from`

I have installed LabCA a half dozen times. After much fighting I landed on the knowledge that the machine/VM must have its host name properly assigned and be a static ip configuration. Additionally, if using your own root and issuer certificate, as I am (I maintain them in an air-gapped XCA repo), the most reliable way to get them to be used for installation is to use PKCS #12 file.

From the information below it seems the boulder image simply is not listening on the ports the system is complaining about. **Am I missing something?** What else can I provide to troubleshoot?

The docker image info is as follows:

#### Docker Image Info

*using the command, docker ps*

| container id | image                                         |
| ------------ | --------------------------------------------- |
| dce3eae95f95 | letsencrypt/boulder-tools:go1.16.6_2021-07-12 |
| 7026fea58953 | letsencrypt/boulder-tools:go1.16.6_2021-07-12 |
| b759a8209548 | mariadb:10.5                                  |

#### IP info

| container id | IPv4                     | name              |
| ------------ | ------------------------ | ----------------- |
| dce3eae95f95 | 10.77.77.77, 10.88.88.88 | boulder_boulder_1 |
| 7026fea58953 | 10.77.77.3               | boulder_labca_1   |
| b759a8209548 | 10.77.77.2               | boulder_bmysql_1  |

#### IP ports 

*using the command, docker port*

| docker image id | ports                                    |
| --------------- | ---------------------------------------- |
| dce3eae95f95    | 4000, 4001, 4002, 4003, 4430, 4431, 8055 |
| 7026fea58953    | 3000                                     |
| b759a8209548    | *nothing returned*                       |

**Comment by hakwerk** [comment]
The many different components of the boulder engine communicate over grpc between some ports internal to the docker container that are not exposed externally. So the fact that these ports are not available from the host machine should not be the problem here.

I usually see a few of those same errors until I finalize the setup in the browser, but it's never more than a handful. So it looks like in your case the boulder-ca instance cannot start properly.
To verify this you could connect to the docker container (docker exec -it boulder_boulder_1 bash) and run
```
ps -ef | grep boulder-ca
```
There should be 2 instances, and the timestamps should be very close to the other instances from a full "ps -ef" output.

If boulder-ca is not running (stably), this usually means something is wrong with the certificate.
From the host machine, try to find the issue by grepping for stuff in the "docker logs boulder_boulder_1" output, e.g.
```
docker logs boulder_boulder_1 2>&1 | grep boulder-ca
```
or look for "certificate", "error" etc to get the relevant error messages that prevents boulder-ca from starting.

**Comment by hakwerk** [comment]
In the latest release of LabCA almost all of these security handshakes no longer occur, so the output should now no longer be flooded with these audit errors.
