### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by XRSec** [hakwerk/labca#39]
I would like to ask, how is the status in your install script done? Can you give me a link, I think it is very interesting
By the way, did your script not take into account the problem of reinstalling after a failed installation

**Comment by XRSec** [comment]
Also, I am writing certificate generation and api , hope you are interested.
With your help, I'm sure we'll be able to build it soon
https://github.com/XRSec/sslt

**Comment by hakwerk** [comment]
I saw the idea somewhere else and tweaked it to my liking. See the "# Color configuration" in the install script together with the msg_*() functions, it's just some ANSI escape sequences, e.g. explained here: https://www.shellhacks.com/bash-colors/ or here: https://techstop.github.io/bash-script-colors/

And yes the script will try to recover from a failed installation, just run it again using the local /home/labca/labca/install script.

**Comment by XRSec** [comment]
@hakwerk thanks, you are great

**Comment by XRSec** [comment]
@hakwerk 

I can understand about the color configuration
Excuse me
How is your status refresh done?
for example 

old
```bash
[~] Start xxxxx
[~] Doing ...
```
new
```bsh
[~] Start xxxxx
[✓] Doing Success
```

I was wondering how you switched `old` to `new`

**Comment by hakwerk** [comment]
There are several parts to that trick.
```
OVER="\\r\\033[K"

msg_info() {
    local msg="$1"
    echo -ne "  ${INFO} ${msg}..."
}

msg_ok() {
    local msg="$1"
    echo -e "${OVER}  ${TICK} ${msg}"
}
```

When writing the old line, the msg_info() uses the **echo** command with the **-n** option, to **not** include a newline character at the end of the text written to screen. So the (invisible) prompt stays at the end of that line after the three dots.

Before writing the new line, the msg_ok() first echo's the $OVER variable which does two things:
- it first prints the **carriage return character "\r"** to move the (invisible) prompt to the start of the line. Because the "\r" is stored in a variable, the escape character "\\" needs to be escaped itself as "\\\\"
- it erases everything to the end of the line with the **special "\033[K" escape sequence**, more info here: [https://askubuntu.com/questions/831971/what-type-of-sequences-are-escape-sequences-starting-with-033#831973](https://askubuntu.com/questions/831971/what-type-of-sequences-are-escape-sequences-starting-with-033#831973)

Now the new text is written starting at the beginning of the line and the old text will no longer be visible, even when the new text is much shorter than the old text.

**Comment by XRSecAdmin** [comment]
Thank you very much. I really didn't notice.
