### ISSUE TITLE
Pre-build docker images

### ISSUE THREAD

**Issue by hakwerk** [hakwerk/labca#41]
Now that everything is running in docker containers, the image(s) should be standard for everyone so we should build them and put them on DockerHub / Github Container Registry.
Probably still need to do some config prep from the control container / commander script when the install script is no longer used.

**Comment by budulinek** [comment]
I understand your decision to "dockerize" everything. It makes sense since Boulder itself is distributed as a dockerfile. But there are problems with docker on some platforms.

I have Proxmox on ZFS filesystem. I use CT (LXC containers) for all my Linux servers.
- It is easy to install Docker directly on the host, but I did not go this way (I want to keep the host clean)
- It is easy to install Docker inside VM, but VMs are resource hungry. Not very efficient.
- I want to have LabCA in CT, but it is quite difficult to install Docker inside (unpriviledged) LXC on ZFS. I had to use some workaround: https://du.nkel.dev/blog/2021-03-25_proxmox_docker/

So I ended up with a "nested" virtualization (docker inside LXC) which is quite difficut to manage and debug. 

BTW, why did you choose Boulder as an ACME server? Why not [step-ca](https://github.com/smallstep/certificates) ?

**Comment by hakwerk** [comment]
> I have Proxmox on ZFS filesystem. I use CT (LXC containers) for all my Linux servers.

I have the exact same setup.

> * It is easy to install Docker inside VM, but VMs are resource hungry. Not very efficient.

That's an exaggeration. I do now have 1 VM with docker next to all my LXC containers (a dozen or so). That is where I am installing any new stuff now, I personally like managing docker containers way better than all the LXC containers!
The CPU usage of VM versus CT is barely different. Only the memory is pre-allocated with a VM but when having only 1 VM (or maybe a few) that is not a problem.

Docker is huge out there and still gaining momentum so it is a good skill to have 😄.

> * I want to have LabCA in CT, but it is quite difficult to install Docker inside (unpriviledged) LXC on ZFS. I had to use some workaround: https://du.nkel.dev/blog/2021-03-25_proxmox_docker/

I never had any issues with docker inside the LXC for LabCA. It's also an unprivileged container but I don't recall if I had to do anything special, maybe things have changed there.

**Comment by budulinek** [comment]
> Docker is huge out there and still gaining momentum so it is a good skill to have 😄.

I know Docker is "IN". But I am just a hobbyist with a home server. I do not work in IT so there is no pressure on me to learn new stuff... Proxmox and LXC is doing the job for me.

With unpriviledged LXC on ZFS I had problem with docker taking more and more disk space. I chose one of two possible solutions described [here](https://forum.proxmox.com/threads/docker-lxc-unprivileged-container-on-proxmox-7-with-zfs.99796/).

Thanks for your replies!

**Comment by hakwerk** [comment]
Included in release v23.05
